# Built with Jekyll 3.2.0

# Setup
title:               Ed.
tagline:             'Mike Solak's personal website.'
description:         'Mike Solak is a future U.S. Army Infantry Officer who enjoys snowboarding and writing code.'
url:                 'http://solak1.github.io'
baseurl:             ''

# About/contact
author:
  name:              Michael Solak
  url:               https://twitter.com/mikesolak
  email:             solak1@canisius.edu

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "Mike"
